import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { createScheduleRuleSchema, parseBody } from "@/lib/validations";
import { requireApiAuth, requireApiRole } from "@/lib/api-auth";
import { materializeRule } from "@/lib/schedule";

const DAY_NAMES = ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"];

export async function GET() {
  const auth = await requireApiAuth();
  if ("error" in auth) return auth.error;

  const rules = await prisma.scheduleRule.findMany({
    include: {
      course: { select: { name: true, code: true } },
      room: { select: { name: true, building: true } },
      _count: { select: { sessions: true } },
    },
    orderBy: [{ dayOfWeek: "asc" }, { startTime: "asc" }],
  });

  return NextResponse.json(
    rules.map((r) => ({ ...r, dayName: DAY_NAMES[r.dayOfWeek] }))
  );
}

export async function POST(req: NextRequest) {
  const auth = await requireApiRole(["ADMIN"]);
  if ("error" in auth) return auth.error;

  try {
    const body = await req.json();
    const parsed = parseBody(createScheduleRuleSchema, body);
    if (!parsed.success) {
      return NextResponse.json({ error: parsed.error }, { status: 400 });
    }

    const { courseId, roomId, dayOfWeek, startTime, endTime, startDate, endDate } = parsed.data;

    // Validate end > start (time and date)
    if (startTime >= endTime) {
      return NextResponse.json(
        { error: "L'heure de fin doit être après l'heure de début" },
        { status: 400 }
      );
    }
    if (new Date(endDate) < new Date(startDate)) {
      return NextResponse.json(
        { error: "La date de fin doit être après la date de début" },
        { status: 400 }
      );
    }

    const rule = await prisma.scheduleRule.create({
      data: {
        courseId,
        roomId,
        dayOfWeek,
        startTime,
        endTime,
        startDate: new Date(startDate),
        endDate: new Date(endDate),
        active: true,
      },
    });

    // Materialize sessions immediately
    const result = await materializeRule(rule.id);

    return NextResponse.json(
      { rule, materialized: result },
      { status: 201 }
    );
  } catch (error) {
    console.error("Schedule rule create error:", error);
    return NextResponse.json({ error: "Erreur serveur" }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest) {
  const auth = await requireApiRole(["ADMIN"]);
  if ("error" in auth) return auth.error;

  const { searchParams } = new URL(req.url);
  const id = searchParams.get("id");
  const deleteSessions = searchParams.get("deleteSessions") === "true";

  if (!id) return NextResponse.json({ error: "ID requis" }, { status: 400 });

  if (deleteSessions) {
    // Delete future sessions generated by this rule (don't touch past ones)
    await prisma.session.deleteMany({
      where: {
        scheduleRuleId: id,
        date: { gte: new Date() },
      },
    });
  }

  await prisma.scheduleRule.delete({ where: { id } });
  return NextResponse.json({ success: true });
}
